# Generated by Django 5.1.2 on 2024-10-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=255)),
                ('cor', models.CharField(max_length=255)),
                ('local_queda', models.CharField(max_length=255)),
                ('armamento', models.CharField(max_length=255)),
                ('combustivel', models.CharField(max_length=255)),
                ('tripulantes', models.CharField(max_length=255)),
                ('avaria', models.CharField(max_length=255)),
                ('potencial_prospecção_tecnologico', models.IntegerField()),
                ('periculosidade', models.IntegerField()),
                ('etiquetas', models.CharField(max_length=255)),
            ],
        ),
    ]
