# Generated by Django 5.1.2 on 2024-10-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pele_esverdeada', models.BooleanField()),
                ('bico_pequeno', models.BooleanField()),
                ('sotaque_esquisito', models.BooleanField()),
                ('local', models.CharField(max_length=255)),
                ('quantidade', models.CharField(max_length=255)),
                ('xenofago', models.BooleanField()),
                ('plano_captura', models.CharField(max_length=255)),
            ],
        ),
    ]
